spring:
  application:
    name: "gatewayserver"
  config:
    import: "configserver:http://configserver:8071/"

info:
    app:
        name: "${spring.application.name}"
        description: "Gateway Server Application"
        version: "1.0.0"